In [7]:
import os
import json
import polars as pl
from ucimlrepo import fetch_ucirepo

import kagglehub
from kagglehub import KaggleDatasetAdapter
# from kaggle.api.kaggle_api_extended import KaggleApi

import mixtabank
from mixtabank.src.utils import get_df_info_pl

In [9]:
# mixtabank.uci_dict

In [ ]:
# # read a JSON file into a dict:
# with open('data_src_dict/UCI.JSON') as f:
#     uci_dict = json.load(f)

In [6]:
# datasets_path = "/Users/leec/Documents/datasets/"

### Petfinder_Tab

In [14]:
dataset_path = "datuman/petfinder-adoption-tabular-only-tables"
file_name = "petfinder_tab_processed.csv"

# Load the file directly into a Polars DataFrame
df = kagglehub.dataset_load(KaggleDatasetAdapter.POLARS, dataset_path, file_name).collect()
df

shape: (14_993, 18)
┌──────┬────────┬──────────────────────┬────────┬───┬─────┬──────────┬──────────┬────────────┐
│ Type ┆ Gender ┆ Breed1               ┆ Color1 ┆ … ┆ Fee ┆ VideoAmt ┆ PhotoAmt ┆ is_adopted │
│ ---  ┆ ---    ┆ ---                  ┆ ---    ┆   ┆ --- ┆ ---      ┆ ---      ┆ ---        │
│ str  ┆ str    ┆ str                  ┆ str    ┆   ┆ i64 ┆ i64      ┆ i64      ┆ i64        │
╞══════╪════════╪══════════════════════╪════════╪═══╪═════╪══════════╪══════════╪════════════╡
│ Cat  ┆ Male   ┆ Tabby                ┆ Black  ┆ … ┆ 100 ┆ 0        ┆ 1        ┆ 1          │
│ Cat  ┆ Male   ┆ Domestic Medium Hair ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 2        ┆ 1          │
│ Dog  ┆ Male   ┆ Mixed Breed          ┆ Brown  ┆ … ┆ 0   ┆ 0        ┆ 7        ┆ 1          │
│ Dog  ┆ Female ┆ Mixed Breed          ┆ Black  ┆ … ┆ 150 ┆ 0        ┆ 8        ┆ 1          │
│ Dog  ┆ Male   ┆ Mixed Breed          ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 3        ┆ 1          │
│ …    ┆ …      ┆ …                    ┆ …      ┆ … ┆ …   ┆ …        ┆ …        ┆ …          │
│ Cat  ┆ Mixed  ┆ Domestic Short Hair  ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 3        ┆ 1          │
│ Cat  ┆ Mixed  ┆ Domestic Medium Hair ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 3        ┆ 0          │
│ Cat  ┆ Mixed  ┆ Domestic Medium Hair ┆ Cream  ┆ … ┆ 30  ┆ 0        ┆ 5        ┆ 1          │
│ Cat  ┆ Female ┆ Domestic Short Hair  ┆ Yellow ┆ … ┆ 0   ┆ 0        ┆ 3        ┆ 0          │
│ Dog  ┆ Male   ┆ Mixed Breed          ┆ Brown  ┆ … ┆ 0   ┆ 0        ┆ 1        ┆ 1          │
└──────┴────────┴──────────────────────┴────────┴───┴─────┴──────────┴──────────┴────────────┘

In [8]:
dataset_name = "petfinder_tab"
prediction_task = "binary_classification"  # ,regression,  multiclass_classification, binary_classification
target_col_name = "is_adopted"


petfinder_dtypes_final = {
    "Type": pl.Utf8,
    "Gender": pl.Utf8,
    "Breed1": pl.Utf8,
    "Color1": pl.Utf8,
    "Color2": pl.Utf8,
    "State": pl.Utf8,
    "Age": pl.Int64,
    "MaturitySize": pl.Int64,
    "FurLength": pl.Int64,
    "Vaccinated": pl.Int64,
    "Dewormed": pl.Int64,
    "Sterilized": pl.Int64,
    "Health": pl.Int64,
    "Quantity": pl.Int64,
    "Fee": pl.Int64,
    "VideoAmt": pl.Int64,
    "PhotoAmt": pl.Int64,
    "is_adopted": pl.Utf8,
}

petfinder_dtypes_final.pop("is_adopted")
catCols = [k for k, v in petfinder_dtypes_final.items() if v == pl.Utf8]
numCols = [k for k, v in petfinder_dtypes_final.items() if v != pl.Utf8]

# Load and preprocess data
petfinder_data_path_train = os.path.join(datasets_path, dataset_name, "train.csv")
petfinder_data_path_test = os.path.join(datasets_path, dataset_name, "test.csv")
petfinder_color_path = os.path.join(datasets_path, dataset_name, "PetFinder-ColorLabels.csv")
petfinder_breed_path = os.path.join(datasets_path, dataset_name, "PetFinder-BreedLabels.csv")
petfinder_state_path = os.path.join(datasets_path, dataset_name, "PetFinder-StateLabels.csv")

dataset = pl.read_csv(petfinder_data_path_train)  # no nulls in this dataset
petfinder_color_df = pl.read_csv(petfinder_color_path)  # color lookup table
petfinder_breed_df = pl.read_csv(petfinder_breed_path)  # breed lookup table
petfinder_state_df = pl.read_csv(petfinder_state_path)  # state lookup table

# Join lookup tables to main dataset, and rename columns.
dataset = (
    dataset.join(petfinder_breed_df, left_on=["Breed1", "Type"], right_on=["BreedID", "Type"], how="left")
    .drop("Breed1")
    .rename({"BreedName": "Breed1"})
)
dataset = (
    dataset.join(petfinder_color_df, left_on="Color1", right_on="ColorID", how="left")
    .drop("Color1")
    .rename({"ColorName": "Color1"})
)
dataset = (
    dataset.join(petfinder_color_df, left_on="Color2", right_on="ColorID", how="left")
    .drop("Color2")
    .rename({"ColorName": "Color2"})
)
dataset = dataset.with_columns(pl.col("Color2").fill_null("NoColor"))
dataset = (
    dataset.join(petfinder_state_df, left_on="State", right_on="StateID", how="left")
    .drop("State")
    .rename({"StateName": "State"})
)

# Create target column and convert some columns to string type.
dataset = dataset.with_columns(pl.when(pl.col("AdoptionSpeed") == 4).then(0).otherwise(1).alias("is_adopted"))
dataset = dataset.with_columns(pl.when(pl.col("Type") == 1).then(pl.lit("Dog")).otherwise(pl.lit("Cat")).alias("Type"))
dataset = dataset.with_columns(
    pl.when(pl.col("Gender") == 1)
    .then(pl.lit("Male"))
    .when(pl.col("Gender") == 2)
    .then(pl.lit("Female"))
    .otherwise(pl.lit("Mixed"))
    .alias("Gender")
)

dataset = dataset.with_columns(pl.col("PhotoAmt").cast(pl.Int64))

# Drop un-used columns.
dataset = dataset.select(catCols + numCols + ["is_adopted"])

# dataset.write_csv(os.path.join(datasets_path,dataset_name,"petfinder_tab_processed.csv"))
# final shape: (14993, 18)

# dataset.null_count().sum()

In [9]:
print(f"Number of numerical columns: {len(numCols)}")
print(f"Number of categorical columns: {len(catCols)}")
print(f"Total cardinality: {sum([dataset[col].n_unique() for col in catCols])}")

Number of numerical columns: 11
Number of categorical columns: 6
Total cardinality: 208

In [4]:
df_info = get_df_info_pl(dataset)
# df_info

NameError: name 'dataset' is not defined

In [3]:
os.environ["KAGGLE_USERNAME"] = "datuman"
os.environ["KAGGLE_KEY"] = "87e8f21e324595550a4dced6a311b355"

api = KaggleApi()
api.authenticate()

In [ ]:
api.dataset_list

In [6]:
# datasets = api.dataset_list(search='home-credit-default-risk')
# print(datasets)

In [18]:


# # Download latest version
# path = kagglehub.dataset_download("megancrenshaw/home-credit-default-risk")

# print("Path to dataset files:", path)

In [5]:
dataset_path = "megancrenshaw/home-credit-default-risk"
file_name = "home-credit-default-risk/application_train.csv"

# Load the file directly into a Polars DataFrame
df = kagglehub.dataset_load(KaggleDatasetAdapter.PANDAS, dataset_path, file_name)#.collect()
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [21]:
df.dtypes

SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     float64
AMT_REQ_CREDIT_BUREAU_WEEK    float64
AMT_REQ_CREDIT_BUREAU_MON     float64
AMT_REQ_CREDIT_BUREAU_QRT     float64
AMT_REQ_CREDIT_BUREAU_YEAR    float64
Length: 122, dtype: object

In [16]:
df

shape: (307_511, 122)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ NAME_CONTR ┆ CODE_GEND ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ ACT_TYPE   ┆ ER        ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ i64        ┆ i64    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ str        ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100002     ┆ 1      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 100003     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 100004     ┆ 0      ┆ Revolving  ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│            ┆        ┆ loans      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 100006     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 100007     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 456251     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 456252     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 456253     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       │
│ 456254     ┆ 1      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 456255     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 2.0       ┆ 0.0       ┆ 1.0       │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Clickstream

In [137]:
 "clickstream":{"uci_id":553,
        "name": "Clickstream Data for Online Retail",
        "repository_url": "https://archive.ics.uci.edu/dataset/553/clickstream+data+for+online+retail",
        "data_url": "https://archive.ics.uci.edu/static/public/553/clickstream+data+for+online+retail.data",
        'target_col': 'buy',
        'prediction_task': 'binary_classification',
        "shape": (287, 13),
    },

SyntaxError: illegal target for annotation (3019678334.py, line 1)

In [ ]:
clickstream_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["clickstream"]["uci_id"])
# target_col_name = "buy"
# prediction_task = "binary_classification"
X = pl.from_pandas(clickstream_data.data.features)
Y = pl.from_pandas(clickstream_data.data.targets)
clickstream = pl.concat([X, Y], how="horizontal")
clickstream

## UCI

In [ ]:
# NAME_URL_DICT_UCI = {
#     "bank-marketing": {
#         "uci_id": 222,
#         "name": "Bank Marketing",
#         "repository_url": "https://archive.ics.uci.edu/dataset/222/bank+marketing",
#         "data_url": "https://archive.ics.uci.edu/static/public/222/data.csv",
#         "target_col": "y",
#         "prediction_task": "binary_classification",
#         "shape": (45211, 17),
#         "types": {"intCols": 7, "floatCols": 10, "boolCols": 1, "catCols": 10},
#     },
#     "adult-census": {
#         "uci_id": 2,
#         "name": "Adult",
#         "repository_url": "https://archive.ics.uci.edu/dataset/2/adult",
#         "data_url": "https://archive.ics.uci.edu/static/public/2/adult.data",
#         "target_col": "income",
#         "prediction_task": "binary_classification",
#         "shape": (48842, 15),
#     },
#     "credit-defualt-taiwan": {
#         "uci_id": 350,
#         "name": "Default of Credit Card Clients",
#         "repository_url": "https://archive.ics.uci.edu/dataset/350/default+of+credit+card+clients",
#         "data_url": "https://archive.ics.uci.edu/static/public/350/default+of+credit+card+clients.data",
#         "target_col": "default payment next month",
#         "prediction_task": "binary_classification",
#         "shape": (30000, 24),
#     },
#     "cdc_diabetes": {
#         "uci_id": 891,
#         "name": "CDC Diabetes Health Indicators",
#         "repository_url": "https://archive.ics.uci.edu/dataset/891/diabetes",
#         "data_url": "https://archive.ics.uci.edu/static/public/891/diabetes.data",
#         "target_col": "Diabetes_binary",
#         "prediction_task": "binary_classification",
#         "shape": (253, 680, 21),
#     },
#     "census-income_full": {
#         "uci_id": 117,
#         "name": "Census Income (KDD)",
#         "repository_url": "https://archive.ics.uci.edu/dataset/117/census+income+kdd",
#         "data_url": "https://archive.ics.uci.edu/static/public/117/census+income+kdd.data",
#         "target_col": "income",
#         "prediction_task": "binary_classification",
#         "shape": (299285, 41),
#     },
#     "support2": {
#         "uci_id": 880,
#         "name": "SUPPORT2",
#         "repository_url": "https://archive.ics.uci.edu/dataset/880/support2",
#         "data_url": "https://archive.ics.uci.edu/static/public/880/support2.data",
#         "target_col": "death",
#         "prediction_task": "binary_classification",
#         "shape": (9105, 21),
#     },
#     "diabetes_130us": {
#         "uci_id": 296,
#         "name": "Diabetes 130-US hospitals for years 1999-2008",
#         "repository_url": "https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008",
#         "data_url": "https://archive.ics.uci.edu/static/public/296/diabetes+130-us+hospitals+for+years+1999-2008.data",
#         "target_col": "readmitted",
#         "prediction_task": "binary_classification",
#         "shape": (130, 50),
#         "types": {"numCols": 27, "catCols": 23},
#     },
#     "nursery": {
#         "uci_id": 76,
#         "name": "Nursery",
#         "repository_url": "https://archive.ics.uci.edu/dataset/76/nursery",
#         "data_url": "https://archive.ics.uci.edu/dataset/76/nursery.data",
#         "target_col": "class",
#         "prediction_task": "multi_class_classification",
#         "shape": (12960, 8),
#     },
#     "taiwanese_bankruptcy": {
#         "uci_id": 572,
#         "name": "Taiwanese Bankruptcy",
#         "repository_url": "https://archive.ics.uci.edu/dataset/572/taiwanese+bankruptcy+prediction",
#         "data_url": "https://archive.ics.uci.edu/dataset/572/taiwanese+bankruptcy+prediction.data",
#         "target_col": "Bankrupt?",
#         "prediction_task": "binary_classification",
#         "shape": (6819, 96),
#     },
#     "apartment_rent_classified": {
#         "uci_id": 555,
#         "name": "Apartment Rent Classified",
#         "repository_url": "https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified",
#         "data_url": "https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified.data",
#         "target_col": ["square_feet", "price"],
#         "prediction_task": "regression",
#         "shape": (99826, 21),
#     },
#     "covertype": {
#         "uci_id": 31,
#         "name": "Covertype",
#         "repository_url": "https://archive.ics.uci.edu/dataset/31/covertype",
#         "data_url": "https://archive.ics.uci.edu/dataset/31/covertype.data",
#         "target_col": "Cover_Type",
#         "prediction_task": "multi_class_classification",
#         "shape": (581012, 55),
#     },
#     # "adult": "https://archive.ics.uci.edu/static/public/2/adult.zip",
#     # "default": "https://archive.ics.uci.edu/static/public/350/default+of+credit+card+clients.zip",
#     # "magic": "https://archive.ics.uci.edu/static/public/159/magic+gamma+telescope.zip",
#     # "shoppers": "https://archive.ics.uci.edu/static/public/468/online+shoppers+purchasing+intention+dataset.zip",
#     # "beijing": "https://archive.ics.uci.edu/static/public/381/beijing+pm2+5+data.zip",
#     # "news": "https://archive.ics.uci.edu/static/public/332/online+news+popularity.zip",
# }

### Bank-Marketing

In [4]:
bank_marketing_data = fetch_ucirepo(id=uci_dict["bank-marketing"]["uci_id"])
X = pl.from_pandas(bank_marketing_data.data.features)
Y = pl.from_pandas(bank_marketing_data.data.targets)
bank_marketing = pl.concat([X, Y], how="horizontal")
bank_marketing

shape: (45_211, 17)
┌─────┬──────────────┬──────────┬───────────┬───┬───────┬──────────┬──────────┬─────┐
│ age ┆ job          ┆ marital  ┆ education ┆ … ┆ pdays ┆ previous ┆ poutcome ┆ y   │
│ --- ┆ ---          ┆ ---      ┆ ---       ┆   ┆ ---   ┆ ---      ┆ ---      ┆ --- │
│ i64 ┆ str          ┆ str      ┆ str       ┆   ┆ i64   ┆ i64      ┆ str      ┆ str │
╞═════╪══════════════╪══════════╪═══════════╪═══╪═══════╪══════════╪══════════╪═════╡
│ 58  ┆ management   ┆ married  ┆ tertiary  ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 44  ┆ technician   ┆ single   ┆ secondary ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 33  ┆ entrepreneur ┆ married  ┆ secondary ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 47  ┆ blue-collar  ┆ married  ┆ null      ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 33  ┆ null         ┆ single   ┆ null      ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ …   ┆ …            ┆ …        ┆ …         ┆ … ┆ …     ┆ …        ┆ …        ┆ …   │
│ 51  ┆ technician   ┆ married  ┆ tertiary  ┆ … ┆ -1    ┆ 0        ┆ null     ┆ yes │
│ 71  ┆ retired      ┆ divorced ┆ primary   ┆ … ┆ -1    ┆ 0        ┆ null     ┆ yes │
│ 72  ┆ retired      ┆ married  ┆ secondary ┆ … ┆ 184   ┆ 3        ┆ success  ┆ yes │
│ 57  ┆ blue-collar  ┆ married  ┆ secondary ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 37  ┆ entrepreneur ┆ married  ┆ secondary ┆ … ┆ 188   ┆ 11       ┆ other    ┆ no  │
└─────┴──────────────┴──────────┴───────────┴───┴───────┴──────────┴──────────┴─────┘

In [5]:
df_info = get_df_info_pl(bank_marketing)
# df_info

DataFrame shape: (45211, 17)
Number of numerical columns: 7: ['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
  - Integer columns: 7: ['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
  - Float columns: 0: []
Number of categorical columns: 10: ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']
  - Binary columns: 4: ['default', 'housing', 'loan', 'y']
  - Boolean columns: 0: []
Total categorical cardinality: 46
Columns with missing values: 4

In [45]:
bank_marketing_data.metadata.keys()

dict_keys(['uci_id', 'name', 'repository_url', 'data_url', 'abstract', 'area', 'tasks', 'characteristics', 'num_instances', 'num_features', 'feature_types', 'demographics', 'target_col', 'index_col', 'has_missing_values', 'missing_values_symbol', 'year_of_dataset_creation', 'last_updated', 'dataset_doi', 'creators', 'intro_paper', 'additional_info'])

In [49]:
bank_marketing_data.metadata["feature_types"]
print(bank_marketing_data.metadata)

['Categorical', 'Integer']

### Adult

In [69]:
adult_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["adult"]["uci_id"])
target_col_name = "is_high_income"
prediction_task = "binary_classification"
X = pl.from_pandas(adult_data.data.features)
Y = pl.from_pandas(adult_data.data.targets)
adult = pl.concat([X, Y], how="horizontal")
adult = adult.with_columns(pl.when(pl.col("income") == ">50K.").then(1).otherwise(0).alias("is_high_income").cast(str))
adult = adult.drop(["income"])  # Drop un-used columns
adult

shape: (48_842, 15)
┌─────┬─────────────┬────────┬───────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ age ┆ workclass   ┆ fnlwgt ┆ education ┆ … ┆ capital-los ┆ hours-per-w ┆ native-cou ┆ is_high_in │
│ --- ┆ ---         ┆ ---    ┆ ---       ┆   ┆ s           ┆ eek         ┆ ntry       ┆ come       │
│ i64 ┆ str         ┆ i64    ┆ str       ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│     ┆             ┆        ┆           ┆   ┆ i64         ┆ i64         ┆ str        ┆ str        │
╞═════╪═════════════╪════════╪═══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 39  ┆ State-gov   ┆ 77516  ┆ Bachelors ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 50  ┆ Self-emp-no ┆ 83311  ┆ Bachelors ┆ … ┆ 0           ┆ 13          ┆ United-Sta ┆ 0          │
│     ┆ t-inc       ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 38  ┆ Private     ┆ 215646 ┆ HS-grad   ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 53  ┆ Private     ┆ 234721 ┆ 11th      ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 28  ┆ Private     ┆ 338409 ┆ Bachelors ┆ … ┆ 0           ┆ 40          ┆ Cuba       ┆ 0          │
│ …   ┆ …           ┆ …      ┆ …         ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ 39  ┆ Private     ┆ 215419 ┆ Bachelors ┆ … ┆ 0           ┆ 36          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 64  ┆ null        ┆ 321403 ┆ HS-grad   ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 38  ┆ Private     ┆ 374983 ┆ Bachelors ┆ … ┆ 0           ┆ 50          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 44  ┆ Private     ┆ 83891  ┆ Bachelors ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 35  ┆ Self-emp-in ┆ 182148 ┆ Bachelors ┆ … ┆ 0           ┆ 60          ┆ United-Sta ┆ 1          │
│     ┆ c           ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
└─────┴─────────────┴────────┴───────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [71]:
df_info = get_df_info(adult)
# df_info

DataFrame shape: (48842, 15)
Number of numerical columns: 6
Number of categorical columns: 9
Total categorical cardinality: 107
Columns with missing values: 3

### Credit-default Taiwan

In [97]:
credit_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["credit-defualt"]["uci_id"])
# target_col_name = "is_default"
# prediction_task = "binary_classification"
X = pl.from_pandas(credit_data.data.features)
Y = pl.from_pandas(credit_data.data.targets)
credit = pl.concat([X, Y], how="horizontal")
# credit = credit.with_columns(
#             pl.when(pl.col("default payment next month") == 1).then(1).otherwise(0).alias("is_default").cast(str)
#         )
# credit = credit.drop(["default payment next month"])  # Drop un-used columns
credit

shape: (30_000, 24)
┌────────┬─────┬─────┬─────┬───┬──────┬───────┬──────┬─────┐
│ X1     ┆ X2  ┆ X3  ┆ X4  ┆ … ┆ X21  ┆ X22   ┆ X23  ┆ Y   │
│ ---    ┆ --- ┆ --- ┆ --- ┆   ┆ ---  ┆ ---   ┆ ---  ┆ --- │
│ i64    ┆ i64 ┆ i64 ┆ i64 ┆   ┆ i64  ┆ i64   ┆ i64  ┆ i64 │
╞════════╪═════╪═════╪═════╪═══╪══════╪═══════╪══════╪═════╡
│ 20000  ┆ 2   ┆ 2   ┆ 1   ┆ … ┆ 0    ┆ 0     ┆ 0    ┆ 1   │
│ 120000 ┆ 2   ┆ 2   ┆ 2   ┆ … ┆ 1000 ┆ 0     ┆ 2000 ┆ 1   │
│ 90000  ┆ 2   ┆ 2   ┆ 2   ┆ … ┆ 1000 ┆ 1000  ┆ 5000 ┆ 0   │
│ 50000  ┆ 2   ┆ 2   ┆ 1   ┆ … ┆ 1100 ┆ 1069  ┆ 1000 ┆ 0   │
│ 50000  ┆ 1   ┆ 2   ┆ 1   ┆ … ┆ 9000 ┆ 689   ┆ 679  ┆ 0   │
│ …      ┆ …   ┆ …   ┆ …   ┆ … ┆ …    ┆ …     ┆ …    ┆ …   │
│ 220000 ┆ 1   ┆ 3   ┆ 1   ┆ … ┆ 3047 ┆ 5000  ┆ 1000 ┆ 0   │
│ 150000 ┆ 1   ┆ 3   ┆ 2   ┆ … ┆ 129  ┆ 0     ┆ 0    ┆ 0   │
│ 30000  ┆ 1   ┆ 2   ┆ 2   ┆ … ┆ 4200 ┆ 2000  ┆ 3100 ┆ 1   │
│ 80000  ┆ 1   ┆ 3   ┆ 1   ┆ … ┆ 1926 ┆ 52964 ┆ 1804 ┆ 1   │
│ 50000  ┆ 1   ┆ 2   ┆ 1   ┆ … ┆ 1000 ┆ 1000  ┆ 1000 ┆ 1   │
└────────┴─────┴─────┴─────┴───┴──────┴───────┴──────┴─────┘

In [85]:
# credit_data.metadata

In [84]:
credit_data.metadata["additional_info"]["variable_info"].split("\r\n")

['This research employed a binary variable, default payment (Yes = 1, No = 0), as the response variable. This study reviewed the literature and used the following 23 variables as explanatory variables:',
 'X1: Amount of the given credit (NT dollar): it includes both the individual consumer credit and his/her family (supplementary) credit.',
 'X2: Gender (1 = male; 2 = female).',
 'X3: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others).',
 'X4: Marital status (1 = married; 2 = single; 3 = others).',
 'X5: Age (year).',
 'X6 - X11: History of past payment. We tracked the past monthly payment records (from April to September, 2005) as follows: X6 = the repayment status in September, 2005; X7 = the repayment status in August, 2005; . . .;X11 = the repayment status in April, 2005. The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; . . .; 8 = payment delay for eight months; 9 = payment delay for nine months and above.',
 'X12-X17: Amount of bill statement (NT dollar). X12 = amount of bill statement in September, 2005; X13 = amount of bill statement in August, 2005; . . .; X17 = amount of bill statement in April, 2005. ',
 'X18-X23: Amount of previous payment (NT dollar). X18 = amount paid in September, 2005; X19 = amount paid in August, 2005; . . .;X23 = amount paid in April, 2005.',
 '']

In [98]:
col_mapping = {
    "X1": "Credit_Amount",
    "X2": "Gender",
    "X3": "Education_Level",
    "X4": "Marital_Status",
    "X5": "Age",
    "X6": "Pay_0",
    "X7": "Pay_2",
    "X8": "Pay_3",
    "X9": "Pay_4",
    "X10": "Pay_5",
    "X11": "Pay_6",
    "X12": "Bill_Amount1",
    "X13": "Bill_Amount2",
    "X14": "Bill_Amount3",
    "X15": "Bill_Amount4",
    "X16": "Bill_Amount5",
    "X17": "Bill_Amount6",
    "X18": "Pay_Amount1",
    "X19": "Pay_Amount2",
    "X20": "Pay_Amount3",
    "X21": "Pay_Amount4",
    "X22": "Pay_Amount5",
    "X23": "Pay_Amount6",
    "Y": "default",
}

catCols = [
    "Gender",
    "Education_Level",
    "Marital_Status",
    "default",
]


credit = credit.rename(col_mapping)
credit = credit.with_columns(pl.col(catCols).cast(pl.Utf8))
credit

shape: (30_000, 24)
┌────────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────────┐
│ Credit_Amo ┆ Gender ┆ Education_ ┆ Marital_St ┆ … ┆ Pay_Amount ┆ Pay_Amoun ┆ Pay_Amoun ┆ default │
│ unt        ┆ ---    ┆ Level      ┆ atus       ┆   ┆ 4          ┆ t5        ┆ t6        ┆ ---     │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str     │
│ i64        ┆        ┆ str        ┆ str        ┆   ┆ i64        ┆ i64       ┆ i64       ┆         │
╞════════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════════╡
│ 20000      ┆ 2      ┆ 2          ┆ 1          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1       │
│ 120000     ┆ 2      ┆ 2          ┆ 2          ┆ … ┆ 1000       ┆ 0         ┆ 2000      ┆ 1       │
│ 90000      ┆ 2      ┆ 2          ┆ 2          ┆ … ┆ 1000       ┆ 1000      ┆ 5000      ┆ 0       │
│ 50000      ┆ 2      ┆ 2          ┆ 1          ┆ … ┆ 1100       ┆ 1069      ┆ 1000      ┆ 0       │
│ 50000      ┆ 1      ┆ 2          ┆ 1          ┆ … ┆ 9000       ┆ 689       ┆ 679       ┆ 0       │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …       │
│ 220000     ┆ 1      ┆ 3          ┆ 1          ┆ … ┆ 3047       ┆ 5000      ┆ 1000      ┆ 0       │
│ 150000     ┆ 1      ┆ 3          ┆ 2          ┆ … ┆ 129        ┆ 0         ┆ 0         ┆ 0       │
│ 30000      ┆ 1      ┆ 2          ┆ 2          ┆ … ┆ 4200       ┆ 2000      ┆ 3100      ┆ 1       │
│ 80000      ┆ 1      ┆ 3          ┆ 1          ┆ … ┆ 1926       ┆ 52964     ┆ 1804      ┆ 1       │
│ 50000      ┆ 1      ┆ 2          ┆ 1          ┆ … ┆ 1000       ┆ 1000      ┆ 1000      ┆ 1       │
└────────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────────┘

### cdc_diabetes

In [102]:
cdc_diabetes_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["cdc_diabetes"]["uci_id"])
# target_col_name = "Diabetes_binary"
# prediction_task = "binary_classification"
X = pl.from_pandas(cdc_diabetes_data.data.features)
Y = pl.from_pandas(cdc_diabetes_data.data.targets)
cdc_diabetes = pl.concat([X, Y], how="horizontal")
cdc_diabetes

shape: (253_680, 22)
┌────────┬──────────┬───────────┬─────┬───┬─────┬───────────┬────────┬─────────────────┐
│ HighBP ┆ HighChol ┆ CholCheck ┆ BMI ┆ … ┆ Age ┆ Education ┆ Income ┆ Diabetes_binary │
│ ---    ┆ ---      ┆ ---       ┆ --- ┆   ┆ --- ┆ ---       ┆ ---    ┆ ---             │
│ i64    ┆ i64      ┆ i64       ┆ i64 ┆   ┆ i64 ┆ i64       ┆ i64    ┆ i64             │
╞════════╪══════════╪═══════════╪═════╪═══╪═════╪═══════════╪════════╪═════════════════╡
│ 1      ┆ 1        ┆ 1         ┆ 40  ┆ … ┆ 9   ┆ 4         ┆ 3      ┆ 0               │
│ 0      ┆ 0        ┆ 0         ┆ 25  ┆ … ┆ 7   ┆ 6         ┆ 1      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 28  ┆ … ┆ 9   ┆ 4         ┆ 8      ┆ 0               │
│ 1      ┆ 0        ┆ 1         ┆ 27  ┆ … ┆ 11  ┆ 3         ┆ 6      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 24  ┆ … ┆ 11  ┆ 5         ┆ 4      ┆ 0               │
│ …      ┆ …        ┆ …         ┆ …   ┆ … ┆ …   ┆ …         ┆ …      ┆ …               │
│ 1      ┆ 1        ┆ 1         ┆ 45  ┆ … ┆ 5   ┆ 6         ┆ 7      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 18  ┆ … ┆ 11  ┆ 2         ┆ 4      ┆ 1               │
│ 0      ┆ 0        ┆ 1         ┆ 28  ┆ … ┆ 2   ┆ 5         ┆ 2      ┆ 0               │
│ 1      ┆ 0        ┆ 1         ┆ 23  ┆ … ┆ 7   ┆ 5         ┆ 1      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 25  ┆ … ┆ 9   ┆ 6         ┆ 2      ┆ 1               │
└────────┴──────────┴───────────┴─────┴───┴─────┴───────────┴────────┴─────────────────┘

In [ ]:
ordinalCols = ["GenHlth", "Education", "Income"]
intCols = ["MentHlth", "PhysHlth", "BMI", "Age"]
binaryCols = [
    "HighBP",
    "HighChol",
    "CholCheck",
    "Smoker",
    "Stroke",
    "HeartDiseaseorAttack",
    "PhysActivity",
    "Fruits",
    "Veggies",
    "HvyAlcoholConsump",
    "AnyHealthcare",
    "NoDocbcCost",
    "DiffWalk",
    "Sex",
    "Diabetes_binary",
]

In [ ]:
len(cdc_diabetes.columns) == len(ordinalCols) + len(intCols) + len(binaryCols)

### Census Income

probably shouldn't not include...

In [114]:
census_income_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["census-income"]["uci_id"])
# target_col_name = "income"
# prediction_task = "binary_classification"
X = pl.from_pandas(census_income_data.data.features)
Y = pl.from_pandas(census_income_data.data.targets)
census_income = pl.concat([X, Y], how="horizontal")
census_income

shape: (199_523, 42)
┌──────┬─────────────────────────────────┬────────┬────────┬───┬─────────┬─────────┬──────┬────────┐
│ AAGE ┆ ACLSWKR                         ┆ ADTINK ┆ ADTOCC ┆ … ┆ WKSWORK ┆ AHRSPAY ┆ year ┆ income │
│ ---  ┆ ---                             ┆ ---    ┆ ---    ┆   ┆ ---     ┆ ---     ┆ ---  ┆ ---    │
│ i64  ┆ str                             ┆ i64    ┆ i64    ┆   ┆ i64     ┆ i64     ┆ i64  ┆ str    │
╞══════╪═════════════════════════════════╪════════╪════════╪═══╪═════════╪═════════╪══════╪════════╡
│ 73   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 58   ┆  Self-employed-not incorporate… ┆ 4      ┆ 34     ┆ … ┆ 52      ┆ 0       ┆ 94   ┆ -50000 │
│ 18   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 9    ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 94   ┆ -50000 │
│ 10   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 94   ┆ -50000 │
│ …    ┆ …                               ┆ …      ┆ …      ┆ … ┆ …       ┆ …       ┆ …    ┆ …      │
│ 87   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 65   ┆  Self-employed-incorporated     ┆ 37     ┆ 2      ┆ … ┆ 52      ┆ 0       ┆ 94   ┆ -50000 │
│ 47   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 52      ┆ 0       ┆ 95   ┆ -50000 │
│ 16   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 32   ┆  Private                        ┆ 42     ┆ 30     ┆ … ┆ 52      ┆ 0       ┆ 94   ┆ -50000 │
└──────┴─────────────────────────────────┴────────┴────────┴───┴─────────┴─────────┴──────┴────────┘

### Support2

In [117]:
support2_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["support2"]["uci_id"])
# target_col_name = "income"
# prediction_task = "binary_classification"
X = pl.from_pandas(support2_data.data.features)
Y = pl.from_pandas(support2_data.data.targets)
support2 = pl.concat([X, Y], how="horizontal")
support2

shape: (9_105, 45)
┌──────────┬────────┬──────────────┬──────────────┬───┬───────────┬───────┬──────────┬─────────────┐
│ age      ┆ sex    ┆ dzgroup      ┆ dzclass      ┆ … ┆ adlsc     ┆ death ┆ hospdead ┆ sfdm2       │
│ ---      ┆ ---    ┆ ---          ┆ ---          ┆   ┆ ---       ┆ ---   ┆ ---      ┆ ---         │
│ f64      ┆ str    ┆ str          ┆ str          ┆   ┆ f64       ┆ i64   ┆ i64      ┆ str         │
╞══════════╪════════╪══════════════╪══════════════╪═══╪═══════════╪═══════╪══════════╪═════════════╡
│ 62.84998 ┆ male   ┆ Lung Cancer  ┆ Cancer       ┆ … ┆ 7.0       ┆ 0     ┆ 0        ┆ null        │
│ 60.33899 ┆ female ┆ Cirrhosis    ┆ COPD/CHF/Cir ┆ … ┆ 1.0       ┆ 1     ┆ 1        ┆ <2 mo.      │
│          ┆        ┆              ┆ rhosis       ┆   ┆           ┆       ┆          ┆ follow-up   │
│ 52.74698 ┆ female ┆ Cirrhosis    ┆ COPD/CHF/Cir ┆ … ┆ 0.0       ┆ 1     ┆ 0        ┆ <2 mo.      │
│          ┆        ┆              ┆ rhosis       ┆   ┆           ┆       ┆          ┆ follow-up   │
│ 42.38498 ┆ female ┆ Lung Cancer  ┆ Cancer       ┆ … ┆ 0.0       ┆ 1     ┆ 0        ┆ no(M2 and   │
│          ┆        ┆              ┆              ┆   ┆           ┆       ┆          ┆ SIP pres)   │
│ 79.88495 ┆ female ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 2.0       ┆ 0     ┆ 0        ┆ no(M2 and   │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆ SIP pres)   │
│ …        ┆ …      ┆ …            ┆ …            ┆ … ┆ …         ┆ …     ┆ …        ┆ …           │
│ 66.073   ┆ male   ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 0.0       ┆ 0     ┆ 0        ┆ null        │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆             │
│ 55.15399 ┆ female ┆ Coma         ┆ Coma         ┆ … ┆ 0.0       ┆ 0     ┆ 0        ┆ null        │
│ 70.38196 ┆ male   ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 2.5253906 ┆ 0     ┆ 0        ┆ null        │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆             │
│ 47.01999 ┆ male   ┆ MOSF w/Malig ┆ ARF/MOSF     ┆ … ┆ 0.0       ┆ 1     ┆ 1        ┆ <2 mo.      │
│          ┆        ┆              ┆              ┆   ┆           ┆       ┆          ┆ follow-up   │
│ 81.53894 ┆ female ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 0.494751  ┆ 1     ┆ 0        ┆ no(M2 and   │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆ SIP pres)   │
└──────────┴────────┴──────────────┴──────────────┴───┴───────────┴───────┴──────────┴─────────────┘

### diabetes_130us

In [119]:
diabetes_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["diabetes_130us"]["uci_id"])
# target_col_name = "income"
# prediction_task = "binary_classification"
X = pl.from_pandas(diabetes_data.data.features)
Y = pl.from_pandas(diabetes_data.data.targets)
diabetes = pl.concat([X, Y], how="horizontal")
diabetes

/opt/miniconda3/envs/mixtabank/lib/python3.13/site-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

shape: (101_766, 48)
┌───────────────┬────────┬─────────┬────────┬───┬──────────────┬────────┬─────────────┬────────────┐
│ race          ┆ gender ┆ age     ┆ weight ┆ … ┆ metformin-pi ┆ change ┆ diabetesMed ┆ readmitted │
│ ---           ┆ ---    ┆ ---     ┆ ---    ┆   ┆ oglitazone   ┆ ---    ┆ ---         ┆ ---        │
│ str           ┆ str    ┆ str     ┆ str    ┆   ┆ ---          ┆ str    ┆ str         ┆ str        │
│               ┆        ┆         ┆        ┆   ┆ str          ┆        ┆             ┆            │
╞═══════════════╪════════╪═════════╪════════╪═══╪══════════════╪════════╪═════════════╪════════════╡
│ Caucasian     ┆ Female ┆ [0-10)  ┆ null   ┆ … ┆ No           ┆ No     ┆ No          ┆ NO         │
│ Caucasian     ┆ Female ┆ [10-20) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ >30        │
│ AfricanAmeric ┆ Female ┆ [20-30) ┆ null   ┆ … ┆ No           ┆ No     ┆ Yes         ┆ NO         │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ Caucasian     ┆ Male   ┆ [30-40) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Male   ┆ [40-50) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ …             ┆ …      ┆ …       ┆ …      ┆ … ┆ …            ┆ …      ┆ …           ┆ …          │
│ AfricanAmeric ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ >30        │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ AfricanAmeric ┆ Female ┆ [80-90) ┆ null   ┆ … ┆ No           ┆ No     ┆ Yes         ┆ NO         │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ Caucasian     ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Female ┆ [80-90) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ No     ┆ No          ┆ NO         │
└───────────────┴────────┴─────────┴────────┴───┴──────────────┴────────┴─────────────┴────────────┘

In [120]:
diabetes.null_count().sum()

shape: (1, 48)
┌──────┬────────┬─────┬────────┬───┬────────────────────────┬────────┬─────────────┬────────────┐
│ race ┆ gender ┆ age ┆ weight ┆ … ┆ metformin-pioglitazone ┆ change ┆ diabetesMed ┆ readmitted │
│ ---  ┆ ---    ┆ --- ┆ ---    ┆   ┆ ---                    ┆ ---    ┆ ---         ┆ ---        │
│ u32  ┆ u32    ┆ u32 ┆ u32    ┆   ┆ u32                    ┆ u32    ┆ u32         ┆ u32        │
╞══════╪════════╪═════╪════════╪═══╪════════════════════════╪════════╪═════════════╪════════════╡
│ 2273 ┆ 0      ┆ 0   ┆ 98569  ┆ … ┆ 0                      ┆ 0      ┆ 0           ┆ 0          │
└──────┴────────┴─────┴────────┴───┴────────────────────────┴────────┴─────────────┴────────────┘

### Nursery

In [123]:
nursery_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["nursery"]["uci_id"])
# target_col_name = "income"
# prediction_task = "binary_classification"
X = pl.from_pandas(nursery_data.data.features)
Y = pl.from_pandas(nursery_data.data.targets)
nursery = pl.concat([X, Y], how="horizontal")
nursery

shape: (12_960, 9)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ parents    ┆ has_nurs  ┆ form     ┆ children ┆ … ┆ finance   ┆ social    ┆ health    ┆ class     │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str       ┆ str      ┆ str      ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ nonprob   ┆ recommend ┆ recommend │
│            ┆           ┆          ┆          ┆   ┆ t         ┆           ┆ ed        ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ nonprob   ┆ priority  ┆ priority  │
│            ┆           ┆          ┆          ┆   ┆ t         ┆           ┆           ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ nonprob   ┆ not_recom ┆ not_recom │
│            ┆           ┆          ┆          ┆   ┆ t         ┆           ┆           ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ slightly_ ┆ recommend ┆ recommend │
│            ┆           ┆          ┆          ┆   ┆ t         ┆ prob      ┆ ed        ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ slightly_ ┆ priority  ┆ priority  │
│            ┆           ┆          ┆          ┆   ┆ t         ┆ prob      ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ slightly_ ┆ priority  ┆ spec_prio │
│            ┆           ┆          ┆          ┆   ┆           ┆ prob      ┆           ┆ r         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ slightly_ ┆ not_recom ┆ not_recom │
│            ┆           ┆          ┆          ┆   ┆           ┆ prob      ┆           ┆           │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ problemat ┆ recommend ┆ spec_prio │
│            ┆           ┆          ┆          ┆   ┆           ┆ ic        ┆ ed        ┆ r         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ problemat ┆ priority  ┆ spec_prio │
│            ┆           ┆          ┆          ┆   ┆           ┆ ic        ┆           ┆ r         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ problemat ┆ not_recom ┆ not_recom │
│            ┆           ┆          ┆          ┆   ┆           ┆ ic        ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [133]:
# total cardinality:
# get_df_info(nursery)

### taiwanese_bankruptcy

In [139]:
bankruptcy_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["taiwanese_bankruptcy"]["uci_id"])
# target_col_name = "Bankrupt?"
# prediction_task = "binary_classification"
X = pl.from_pandas(bankruptcy_data.data.features)
Y = pl.from_pandas(bankruptcy_data.data.targets)
bankruptcy = pl.concat([X, Y], how="horizontal")
bankruptcy

shape: (6_819, 96)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ROA(C)    ┆ ROA(A)    ┆ ROA(B)    ┆ Operating ┆ … ┆ Interest  ┆ Net       ┆ Equity to ┆ Bankrupt │
│ before    ┆ before    ┆ before    ┆ Gross     ┆   ┆ Coverage  ┆ Income    ┆ Liability ┆ ?        │
│ interest  ┆ interest  ┆ interest  ┆ Margin    ┆   ┆ Ratio     ┆ Flag      ┆ ---       ┆ ---      │
│ and de…   ┆ and % …   ┆ and de…   ┆ ---       ┆   ┆ (Inte…    ┆ ---       ┆ f64       ┆ i64      │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ i64       ┆           ┆          │
│ f64       ┆ f64       ┆ f64       ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.370594  ┆ 0.424389  ┆ 0.40575   ┆ 0.601457  ┆ … ┆ 0.56405   ┆ 1         ┆ 0.016469  ┆ 1        │
│ 0.464291  ┆ 0.538214  ┆ 0.51673   ┆ 0.610235  ┆ … ┆ 0.570175  ┆ 1         ┆ 0.020794  ┆ 1        │
│ 0.426071  ┆ 0.499019  ┆ 0.472295  ┆ 0.60145   ┆ … ┆ 0.563706  ┆ 1         ┆ 0.016474  ┆ 1        │
│ 0.399844  ┆ 0.451265  ┆ 0.457733  ┆ 0.583541  ┆ … ┆ 0.564663  ┆ 1         ┆ 0.023982  ┆ 1        │
│ 0.465022  ┆ 0.538432  ┆ 0.522298  ┆ 0.598783  ┆ … ┆ 0.575617  ┆ 1         ┆ 0.03549   ┆ 1        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.493687  ┆ 0.539468  ┆ 0.54323   ┆ 0.604455  ┆ … ┆ 0.566193  ┆ 1         ┆ 0.02989   ┆ 0        │
│ 0.475162  ┆ 0.538269  ┆ 0.524172  ┆ 0.598308  ┆ … ┆ 0.566018  ┆ 1         ┆ 0.038284  ┆ 0        │
│ 0.472725  ┆ 0.533744  ┆ 0.520638  ┆ 0.610444  ┆ … ┆ 0.565158  ┆ 1         ┆ 0.097649  ┆ 0        │
│ 0.506264  ┆ 0.559911  ┆ 0.554045  ┆ 0.60785   ┆ … ┆ 0.565302  ┆ 1         ┆ 0.044009  ┆ 0        │
│ 0.493053  ┆ 0.570105  ┆ 0.549548  ┆ 0.627409  ┆ … ┆ 0.565167  ┆ 1         ┆ 0.233902  ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [141]:
# dict(zip(bankruptcy.columns, bankruptcy.dtypes))

### apartment_rent_classified

In [ ]:
# floatCols = ["bathrooms","latitude","longitude","time"]
# intCols = ["price","price_display","square_feet","bedrooms","latitude","longitude","time"]

In [166]:
apartment_rent_data["data"]["features"].shape

(99826, 21)

In [164]:
apartment_rent_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["apartment_rent_classified"]["uci_id"])
# target_col_name = "Bankrupt?"
# prediction_task = "binary_classification"
# X = pl.from_pandas(apartment_rent_data.data.features)
# Y = pl.from_pandas(apartment_rent_data.data.targets)
# apartment_rent = pl.concat([X, Y], how="horizontal")
# apartment_rent

/opt/miniconda3/envs/mixtabank/lib/python3.13/site-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (0,5,6,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

### Covertype

In [ ]:
covertype = fetch_ucirepo(id=31)

In [179]:
# covertype["data"]["features"].nunique()
# covertype["data"]["features"].dtypes